#include <ButtonConstants.au3>
#include <GUIConstantsEx.au3>
#include <ListViewConstants.au3>
#include <ProgressConstants.au3>
#include <WindowsConstants.au3>
#include <GuiListView.au3>
#include <WinAPI.au3>
#include <Windowsconstants.au3>

Dim $item[11]
Global $Form1_1 = GUICreate("Auto Login", 450, 300)
Global $btnLogin = GUICtrlCreateButton("Đăng nhập", 16, 250, 105, 33)
Global $btnLogout = GUICtrlCreateButton("Đăng xuất", 172, 250, 105, 33)
Global $lstAccount = GUICtrlCreateListView("|Tên nhân vật   |   Nhân vật thứ|   Vị trí màn hình thứ", 16, 8, 417, 233,-1,$LVS_EX_CHECKBOXES) ;$LVS_EX_CHECKBOXES th?check box v?listview
$item[1] = GUICtrlCreateListViewItem("|Quách Tỉnh|               1|               1", $lstAccount)
$item[2] = GUICtrlCreateListViewItem("|MichaelJackson|               2|               4", $lstAccount)
$item[3] = GUICtrlCreateListViewItem("|tinhbidx|               1|               2", $lstAccount)
$item[4] = GUICtrlCreateListViewItem("|tinhbidx2-NoneName|               1|               3", $lstAccount)
$item[5] = GUICtrlCreateListViewItem("|tinhbidx2-PROVINCE|               2|               3", $lstAccount)
$item[6] = GUICtrlCreateListViewItem("|tinhbidx3|               1|               2", $lstAccount)
$item[7] = GUICtrlCreateListViewItem("|tinhbidx4|               1|               3", $lstAccount)
$item[8] = GUICtrlCreateListViewItem("|tinhbidx5|               1|               2", $lstAccount)
$item[9] = GUICtrlCreateListViewItem("|tinhbidx00|               1|               2", $lstAccount)
$item[10] = GUICtrlCreateListViewItem("|tinhbidx01|               1|               3", $lstAccount)

GUICtrlSendMsg(-1, $LVM_SETCOLUMNWIDTH, 0, 30)
GUICtrlSendMsg(-1, $LVM_SETCOLUMNWIDTH, 1, 150)
GUICtrlSendMsg(-1, $LVM_SETCOLUMNWIDTH, 2, 120)
Global $btnExit = GUICtrlCreateButton("Thoát", 330, 250, 105, 33)
;~ Global $Progress1 = GUICtrlCreateProgress(16, 248, 248, 25)
GUISetState(@SW_SHOW)
#EndRegion ### END Koda GUI section ###

Global $Paused
HotKeySet("{F1}", "TogglePause")
HotKeySet("{ESC}", "Terminate")
Func TogglePause()
	$Paused = Not $Paused
	While $Paused
		Sleep(100)
		ToolTip('Đã dừng (Nhấn ESC để Thoát - F1 để Play/Pause)', 0, 0)
	WEnd
	ToolTip("")
EndFunc   ;==>TogglePause

Func Terminate()
	Exit 0
EndFunc   ;==>Terminate

While 1
	$nMsg = GUIGetMsg()
	Switch $nMsg
		Case $GUI_EVENT_CLOSE
			Exit
			Case $btnLogin
				For $x = 1 to 10
					If _GUICtrlListView_GetItemChecked($lstAccount,$x-1) Then
					Switch $x
						Case 1
							Run("D:\VLNT\Game.exe", "D:\VLNT")
							Sleep(1000)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							ControlSend("","","","tinhnguyendangdx")
							Sleep(500)
							Send("{ENTER}")
							ControlSend("","","","tinhbi")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
						Case 2
							Run("D:\VLNT\Game.exe", "D:\VLNT")
							Sleep(500)
							MouseClickDrag($MOUSE_CLICK_LEFT, 398, 9, 955, 9,0)
							MouseMove(955,174)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							ControlSend("","","","nguyendangtinhdx")
							Sleep(1000)
							Send("{ENTER}")
							ControlSend("","","","812237559")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							MouseClick("left", 1117, 348, 1,5)
							Sleep(500)
							Send("{ENTER}")
						Case 3
							Run("D:\VLNT\Game.exe", "D:\VLNT")
							Sleep(500)
							MouseClickDrag($MOUSE_CLICK_LEFT, 398, 9, 577, 9,0)
							MouseMove(577,174)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							ControlSend("","","","tinhbidx")
							Sleep(1000)
							Send("{ENTER}")
							ControlSend("","","","812237559")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
						Case 4
							Run("D:\VLNT\Game.exe", "D:\VLNT")
							Sleep(500)
							MouseClickDrag($MOUSE_CLICK_LEFT, 398, 9, 788, 9,0)
							MouseMove(788,174)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							ControlSend("","","","tinhbidx2")
							Sleep(1000)
							Send("{ENTER}")
							ControlSend("","","","812237559")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
						Case 5
							Run("D:\VLNT\Game.exe", "D:\VLNT")
							Sleep(500)
							MouseClickDrag($MOUSE_CLICK_LEFT, 398, 9, 788, 9,0)
							MouseMove(788,174)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							ControlSend("","","","tinhbidx2")
							Sleep(1000)
							Send("{ENTER}")
							ControlSend("","","","812237559")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							MouseClick("left", 792, 339, 1,5)
							Sleep(500)
							Send("{ENTER}")
						Case 6
							Run("D:\VLNT\Game.exe", "D:\VLNT")
							Sleep(500)
							MouseClickDrag($MOUSE_CLICK_LEFT, 398, 9, 577, 9,0)
							MouseMove(577,174)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							ControlSend("","","","tinhbidx3")
							Sleep(1000)
							Send("{ENTER}")
							ControlSend("","","","812237559")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
						Case 7
							Run("D:\VLNT\Game.exe", "D:\VLNT")
							Sleep(500)
							MouseClickDrag($MOUSE_CLICK_LEFT, 398, 9, 788, 9,0)
							MouseMove(788,174)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							ControlSend("","","","tinhbidx4")
							Sleep(1000)
							Send("{ENTER}")
							ControlSend("","","","812237559")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
						Case 8
							Run("D:\VLNT\Game.exe", "D:\VLNT")
							Sleep(500)
							MouseClickDrag($MOUSE_CLICK_LEFT, 398, 9, 577, 9,0)
							MouseMove(577,174)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							ControlSend("","","","tinhbidx5")
							Sleep(1000)
							Send("{ENTER}")
							ControlSend("","","","812237559")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
						Case 9
							Run("D:\VLNT\Game.exe", "D:\VLNT")
							Sleep(500)
							MouseClickDrag($MOUSE_CLICK_LEFT, 398, 9, 577, 9,0)
							MouseMove(577,174)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							ControlSend("","","","tinhbidx00")
							Sleep(1000)
							Send("{ENTER}")
							ControlSend("","","","812237559")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
						Case 10
							Run("D:\VLNT\Game.exe", "D:\VLNT")
							Sleep(500)
							MouseClickDrag($MOUSE_CLICK_LEFT, 398, 9, 788, 9,0)
							MouseMove(788,174)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							ControlSend("","","","tinhbidx01")
							Sleep(1000)
							Send("{ENTER}")
							ControlSend("","","","812237559")
							Sleep(500)
							Send("{ENTER}")
							Sleep(500)
							Send("{ENTER}")
					EndSwitch
				EndIf
			Next
		Case $btnLogout
			MouseClick("left", 60, 12, 1,5)
			MouseClick("left", 780, 12, 1,5)
			Send("{ENTER}")
			MouseClick("left", 960, 12, 1,5)
			Send("{ENTER}")
			MouseClick("left", 1170, 12, 1,5)
			Send("{ENTER}")
			MouseClick("left", 1338, 12, 1,5)
			Send("{ENTER}")
		Case $btnExit
			Exit
	EndSwitch
WEnd
